---
services:
  clickhouse:
    image: 'clickhouse/clickhouse-server:latest'
    ports:
      - "8123:8123"
    volumes:
      - ./chdata:/var/lib/clickhouse:Z
      - ./import:/var/lib/clickhouse/user_files:Z
